Arguments and variable node identification in lambda expressions
ml4ai/automates pull request #197
Opened 2021-03-19 13:58 UTC by pauldhein

Another incremental step towards converting lambda expressions into function networks for GrFN 3.0.0

2021-03-23 15:57 UTC, pauldhein commented
@dpdicken this branch is ready for you to add a quick review.

2021-03-31 16:37 UTC, dpdicken requested changes

2021-03-31 17:22 UTC, pauldhein commented on scripts/model_assembly/grfn2pdf.py
> +from dataclasses import dataclass
Probably because I was typing in the wrong file at some point in time ... I'll remove this. Good catch!

2021-04-11 22:36 UTC, pauldhein commented
Hey @dpdicken let me know if the conversations you started in this thread are ready to be resolved. Also I think this code is ready for you to re-review.

2021-04-27 15:49 UTC, dpdicken approved these changes

2021-04-28 15:38 UTC, merged