Unit and param men fix dec2021
ml4ai/automates pull request #281
Opened 2021-12-19 00:01 UTC by maxaalexeeva

- remove param setting mentions if there are more complete, overlapping interval param settings 
- disallow ParamAndUnit mentions that have more than one identifier (each mention should be associated with only one identifier)
- added a copyWithFoundBy method (for easier labeling of mentions with actions involved in their creation), e.g., here, the mention has been produced by the `var-word-equals_value-token` and the `assembleVarsWithParamsAndUnits` action:
```
List(ParamAndUnit, Event) => refugee move speed is equal to 200 
     ------------------------------ 
     Rule => var-word-equals_value-token++assembleVarsWithParamsAndUnits 
     Type => RelationMention 
     ------------------------------ 
     value (Value, Measurement, Phrase, Entity) => 200 
     unit (Unit, Measurement, Phrase, Entity) => km per day 
     variable (Phrase, Entity) => refugee move speed 
```
- removed ValueAndUnit (not being used)

2021-12-19 02:14 UTC, alicekwak requested changes
This is great, thank you @maxaalexeeva! Would you be able to move "UnitRelation" from Entity to Event? Except for that, everything seems perfect :)

2021-12-19 02:14 UTC, alicekwak commented on automates/text_reading/src/main/resources/org/clulab/aske_automates/grammars/taxonomy.yml
>            - UnitRelation
Would you be able to move `UnitRelation` from Entity to Event?

2021-12-19 02:18 UTC, alicekwak commented
Oops, and it looks like one ParameterSetting test (u5a) is failing. The test sentence is this: 

> For the purposes of model parameterisation the value of shoot_lag has been assumed to be around 40 o Cd.

It's failing because "value of shoot_lag" is captured as a variable instead of "shoot_lag". Do you have any idea why this change occurred?

2021-12-19 17:42 UTC, maxaalexeeva commented
@alicekwak 

> It's failing because "value of shoot_lag" is captured as a variable instead of "shoot_lag". 

Nooooo! That was one of those accidentally fixed tests and now it broke again because of who knows what! Bummer.

2021-12-19 23:13 UTC, alicekwak approved these changes
Thank you for the revision! Looks awesome :)

2021-12-20 12:50 UTC, cl4yton approved these changes
From what I understand, this looks good. Thanks!

2021-12-20 18:12 UTC, merged